title: Mint Explained
description: Linux Mint und Linuxcafe Stuttgart
theme: just-the-docs

url: "https://harald-u.github.io/mint-explained"

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
footer_content: "This work is licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a><img src='https://mirrors.creativecommons.org/presskit/icons/cc.svg' alt='' style='max-width: 1em;max-height:1em;margin-left: .2em;'><img src='https://mirrors.creativecommons.org/presskit/icons/by.svg' alt='' style='max-width: 1em;max-height:1em;margin-left: .2em;'><img src='https://mirrors.creativecommons.org/presskit/icons/sa.svg' alt='' style='max-width: 1em;max-height:1em;margin-left: .2em;'>"
last_edit_timestamp: true 
last_edit_time_format: "%d.%m.%Y" 
