title: Mint Explained
description: Linux Mint und Linuxcafe Stuttgart
theme: just-the-docs

baseurl: "/mint-explained"
url: "https://harald-u.github.io"

# Disable .html in page URLs
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
footer_content: 
last_edit_timestamp: true 
last_edit_time_format: "%d.%m.%Y" 
