title: Mint Explained
description: Linux Mint Systemeisntellungen
theme: just-the-docs

url: https://Harald-U.github.io/mint-explained

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
