title: Mint Explained
description: Linux Mint und Linuxcafe Stuttgart
theme: just-the-docs

url: https://Harald-U.github.io/mint-explained

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
footer_content: "Distributed by an <a href=\"https://raw.githubusercontent.com/Harald-U/mint-explained/refs/heads/main/LICENSE\">MIT license.</a>  <img src="{{ site.baseurl }}/assets/cc-by-nc-sa.png" alt="CC BY-NC-SA">"

